### ISSUE TITLE
Installation error: Can't exec "aclocal" (macOS)

### ISSUE THREAD

**Issue by Nakilon** [camertron/python3-parser-rb#1]
```none
$ gem install python3-parser
Fetching: rice-2.2.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing python3-parser:
	ERROR: Failed to build gem native extension.

    current directory: /Users/nakilon/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/rice-2.2.0
/Users/nakilon/.rbenv/versions/2.4.9/bin/ruby -r ./siteconf20210626-87085-omqkcy.rb extconf.rb
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 274.
autoreconf: error: aclocal failed with exit status: 2
post-autoconf.rb:6:in `initialize': No such file or directory @ rb_sysopen - configure (Errno::ENOENT)
	from post-autoconf.rb:6:in `open'
	from post-autoconf.rb:6:in `process'
	from post-autoconf.rb:16:in `<main>'
Post-processing configure
sh: configure: No such file or directory

Makefile not found
...
```

**Comment by Nakilon** [comment]
```bash
brew install automake
```
